### PR TITLE
Restaurant Page

### PR DESCRIPTION
**Pull request by 0x1100010010**
The project includes steps:
- Added npm, Webpack
- Added basic Html skeleton
- Added codefactory.js with HTML generation logic
- Added different JavaScript modules to inject Html content
- Create a production-ready project in the dist folder
- Add README.md

### CODE REVIEW

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required 🛑♻**

<hr>

Hello there :)
Great work and effort you put into this project. Well done!

<hr>

**To Highlight**

Linter✔
README✔
Commits✔
PR✔
Code Division✔
Webpack Configuration✔

<hr>

**To Improve**

- [x] Please make sure to set up the missing scripts inside the package JSON file. It'd be better if you apply a script for Dev mode and another for Production mode.
scripts_requirement

```
"dev": "webpack --mode development",
"build": "webpack --mode production",
```
- [x] Please add the CLI ```npm run build``` in your README file as part of the instructions' steps. 

<hr>

**Nice To Have**

- It'd be great if you add another script to start a localhost server and another script to watch the changes you make while in Dev mode, then update the live server automatically.
```
"watch": "webpack --progress --watch"
"start": "webpack-dev-server --mode development --open"
```
<hr>

Good luck and happy coding 👨‍💻💻
Please feel free to contact me on Slack with the name "Mahmoud Bakr" if you had any questions.

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Changes Required :red_circle:
To Highlight: :angel:

- All necessarily used packages are  included in package.json :+1: 

To Improve :factory_worker: (REQUIRED)

- [x] Please use **arrow** functions instead of the **function** keyword everywhere in your project as you are using ES6  syntax ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/es6_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622983/)).
- [x] I got error when I run `npm start` :

I suggest that you change your start script with:
`"start": "webpack serve"`
And your webpack packages like this:
```
"webpack": "^5.10.0",
"webpack-cli": "^4.2.0",
"webpack-dev-server": "^3.11.0"
```

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @bashforger  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [x] I could check your app from the live demo but not from a local server by running `npm start`. I'll give some screenshots below, and please fix this issue before moving on.
Screenshot from 2021-04-05 13-07-36
###  When I run npm run start, this page is on the screen.
Screenshot from 2021-04-05 13-09-05
:warning: As you can see  in the terminal, if you can see the webpack is served from / but not from the dist/index.html.So your script is not working with your webpack configuration. Kindly fix this issue.
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by 0x1100010010** [comment]
That's because the build directory is `dist`, I will have to remove `dist` to enable it to work in root dir. So click `dist` to open webpage.

**Review by mikenath223 — APPROVED** [review]
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

**Comment by 0x1100010010** [comment]
Thanks man!

**Pull request merged**
